"""Verified facts: the official numbers for a selection, as plain data and sentences.

These facts are computed by the KPI engine (never by AI).  They are shown on the
dashboard as-is and are the ONLY information given to the AI for commentary."""
from __future__ import annotations

from opspulse.engine import kpi as K
from opspulse.engine.analytics import Analyzer
from opspulse.engine.hierarchy import Scope

STATUS_TEXT = {"green": "Green", "amber": "Amber", "red": "Red", "insufficient": "Insufficient data",
               "no_data": "No data", "not_due": "Not yet due"}


def _fmt(az: Analyzer, v, k) -> str:
    return K.format_value(v, k.unit, k.decimals, az.currency)


def _direction_word(k) -> str | None:
    if k.actual is None or k.previous is None:
        return None
    if round(k.actual, k.decimals) == round(k.previous, k.decimals):
        return "unchanged"
    better = (k.actual > k.previous) if k.direction == "higher_better" else (k.actual < k.previous)
    return "improved" if better else "worsened"


def build(az: Analyzer, scope: Scope, period: K.Period, risk_limit: int = 5) -> dict:
    res = az.evaluate(scope, period)
    prev = az.evaluate(scope, period.previous_month(), with_previous=False)
    risks = az.risks(scope, period)
    level = az.child_level(scope)
    ranking = az.compare(scope, period, level) if level else None
    kpis = []
    for k in res.kpis:
        kpis.append({
            "code": k.code, "name": k.name, "actual": None if k.actual is None else round(k.actual, k.decimals),
            "actual_text": _fmt(az, k.actual, k), "target_text": _fmt(az, k.target, k),
            "target": k.target, "status": STATUS_TEXT.get(k.rag, k.rag), "meets_target": k.meets_target,
            "previous_month": None if k.previous is None else round(k.previous, k.decimals),
            "previous_text": _fmt(az, k.previous, k), "change_vs_previous": _direction_word(k),
            "data_received": None if k.coverage is None else f"{k.coverage:.0%}", "weight": k.weight,
        })
    facts = {
        "data_label": "SYNTHETIC DEMO DATA" if az.bundle.org.get("is_demo") else "Approved operational data",
        "organisation": az.bundle.org["name"],
        "selection": scope.label,
        "period": period.label,
        "previous_period": period.previous_month().label,
        "data_as_of": str(az.as_of),
        "health_score": res.score,
        "health_status": STATUS_TEXT.get(res.status, res.status),
        "health_score_previous_month": prev.score,
        "data_coverage": None if res.coverage is None else f"{res.coverage:.0%}",
        "kpis_meeting_target": f"{res.met} of {len(res.scored)}",
        "critical_alerts": az.critical_alerts(scope, period),
        "kpis": kpis,
        "top_risks": [{"where": r.scope_label, "kpi": r.kpi_name, "detail": r.detail}
                      for r in risks if r.kind == "performance"][:risk_limit],
        "data_gaps": [{"where": r.scope_label, "kpi": r.kpi_name, "detail": r.detail}
                      for r in risks if r.kind == "data_gap"][:risk_limit],
        "ranking_level": level,
        "ranking": [] if ranking is None or ranking.empty else [
            {"name": r["name"], "health_score": r["score"], "status": STATUS_TEXT.get(r["status"], r["status"])}
            for r in ranking.sort_values("score", ascending=False, na_position="last").to_dict("records")],
        "health_rule": ("Weighted RAG points per site (Green {g:.0f}, Amber {a:.0f}, Red {r:.0f}); KPIs without data are "
                        "excluded and lower data coverage; multi-site selections average their site scores."
                        ).format(g=res.rules["points"]["green"], a=res.rules["points"]["amber"],
                                 r=res.rules["points"]["red"]),
    }
    return facts


def sentences(f: dict) -> list[str]:
    """Plain-English verified statements generated by rules (no AI)."""
    out = []
    if f["health_score"] is not None:
        line = f"Operational health for {f['selection']} in {f['period']} is {f['health_score']:.1f} ({f['health_status']})"
        if f["health_score_previous_month"] is not None:
            diff = f["health_score"] - f["health_score_previous_month"]
            line += f", {'up' if diff > 0 else 'down' if diff < 0 else 'unchanged'}"
            line += f" {abs(diff):.1f} points from {f['previous_period']}" if diff else f" from {f['previous_period']}"
        out.append(line + ".")
    else:
        out.append(f"No health score can be calculated for {f['selection']} in {f['period']} (no data).")
    out.append(f"On combined figures for the selection, {f['kpis_meeting_target']} KPIs meet target; "
               f"{f['critical_alerts']} red KPI result(s) at process-site level; data coverage is "
               f"{f['data_coverage'] or 'n/a'}.")
    worse = [k for k in f["kpis"] if k["change_vs_previous"] == "worsened"]
    if worse:
        out.append("Worsened vs previous month: " + ", ".join(
            f"{k['name']} ({k['previous_text']} → {k['actual_text']})" for k in worse[:4]) + ".")
    if f["top_risks"]:
        r = f["top_risks"][0]
        out.append(f"Largest risk: {r['kpi']} at {r['where']} – {r['detail']}.")
    if f["data_gaps"]:
        g = f["data_gaps"][0]
        out.append(f"Data gap: {g['kpi']} at {g['where']} – {g['detail']}.")
    if len(f["ranking"]) > 1 and f["ranking"][0]["health_score"] is not None:
        scored = [r for r in f["ranking"] if r["health_score"] is not None]
        out.append(f"Highest {f['ranking_level'].replace('_', ' ')}: {scored[0]['name']} ({scored[0]['health_score']:.1f}); "
                   f"lowest: {scored[-1]['name']} ({scored[-1]['health_score']:.1f}).")
    return out
